//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordBank.Repository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordBank.Repository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;words&gt;
        ///  &lt;word&gt;accommodate&lt;/word&gt;
        ///  &lt;word&gt;accommodation&lt;/word&gt;
        ///  &lt;word&gt;achieve&lt;/word&gt;
        ///  &lt;word&gt;aggressive&lt;/word&gt;
        ///  &lt;word&gt;apparently&lt;/word&gt;
        ///  &lt;word&gt;appearance&lt;/word&gt;
        ///  &lt;word&gt;basically&lt;/word&gt;
        ///  &lt;word&gt;beginning&lt;/word&gt;
        ///  &lt;word&gt;believe&lt;/word&gt;
        ///  &lt;word&gt;business&lt;/word&gt;
        ///&lt;/words&gt;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;words&gt;
        ///  &lt;word id =&quot;1&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;2&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;3&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;4&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;5&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;6&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;7&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;8&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;9&quot;&gt;Embarassed&lt;/word&gt;
        ///  &lt;word id =&quot;10&quot;&gt;Embarassed&lt;/word&gt;
        ///&lt;/words&gt;.
        /// </summary>
        internal static string words_test {
            get {
                return ResourceManager.GetString("words_test", resourceCulture);
            }
        }
    }
}
