//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordBank.Repository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordBank.Repository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;words&gt;
        ///  &lt;word&gt;absence&lt;/word&gt;
        ///  &lt;word&gt;acceptable&lt;/word&gt;
        ///  &lt;word&gt;accidently&lt;/word&gt;
        ///  &lt;word&gt;accommodate&lt;/word&gt;
        ///  &lt;word&gt;accommodation&lt;/word&gt;
        ///  &lt;word&gt;accomplishments&lt;/word&gt;
        ///  &lt;word&gt;accumulate&lt;/word&gt;
        ///  &lt;word&gt;achieve&lt;/word&gt;
        ///  &lt;word&gt;achieveable&lt;/word&gt;
        ///  &lt;word&gt;acknowledge&lt;/word&gt;
        ///  &lt;word&gt;acknowledgement&lt;/word&gt;
        ///  &lt;word&gt;acquaintance&lt;/word&gt;
        ///  &lt;word&gt;acquire&lt;/word&gt;
        ///  &lt;word&gt;across&lt;/word&gt;
        ///  &lt;word&gt;address&lt;/word&gt;
        ///  &lt;word&gt;administratively&lt;/word&gt;
        ///  &lt;word&gt;aggravate&lt;/wor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wordsDefault {
            get {
                return ResourceManager.GetString("wordsDefault", resourceCulture);
            }
        }
    }
}
